import type { Lang } from "@/components/CurrencyProvider";

// Bilingual site content. English is the source of truth; Danish is shown when
// the visitor picks DKK (kr.). Translations are written to read naturally, not
// word-for-word. This is a test to gauge whether localising for other markets
// lifts conversion.

const en = {
  nav: {
    links: [
      ["How it works", "/#how"],
      ["Why FadeClipper", "/#compare"],
      ["Reviews", "/#reviews"],
      ["FAQ", "/#faq"],
    ] as [string, string][],
    getYours: "Get yours",
    offerEndsIn: "Offer ends in",
    launchSale: "40% off — Launch Sale",
    reviews: "reviews",
    subline: "+ free kit & 14-day guarantee",
    bladeBullet: "45° auto-fade blade",
    waterproofBullet: "Waterproof, 240-min battery",
    buyNow: "Buy Now",
    startingCheckout: "Starting checkout…",
  },
  hero: {
    reviews: "reviews",
    h1a: "Fade your own hair.",
    h1b: "In minutes.",
    subA: "The auto-fading clipper with a 45° blade that blends the gradient for you — ",
    subEmph: "no skill needed",
    orderNow: "Order now — ",
    securePayment: "Secure payment",
    guarantee: "14-day guarantee",
    videoAlt: "FadeClipper auto-fading cordless hair clipper",
  },
  press: { seenIn: "As seen in…" },
  how: {
    eyebrow: "60-second setup",
    title: "How does it work?",
    sub: "No experience needed. If you can comb your hair, you can run a FadeClipper.",
    steps: [
      { title: "Charge & power on", text: "Drop it on the dock until full, then tap the power button. The live display shows battery and runtime left." },
      { title: "Pick your fade length", text: "Slide the lever to 0.4, 0.8 or 1.2mm. Start low and tight at the neckline, then step up as you move higher." },
      { title: "Glide across the fade", text: "Hold it flat and level to the skin and glide it straight across the side. The blade blends the gradient for you." },
      { title: "Blend & finish", text: "Step the length up a notch and pass a little higher to melt the lines into a smooth, sharp fade." },
    ],
  },
  compare: {
    eyebrow: "The difference",
    title: "Why FadeClipper beats ordinary clippers.",
    sub: "The auto-fade blade does what regular clippers can't — and what the barber charges you for, on repeat.",
    cols: ["FadeClipper", "Ordinary", "Barber"],
    you: "You",
    rows: [
      { label: "Auto-fades & blends for you", values: [true, false, true] },
      { label: "No skill or 2nd mirror needed", values: [true, false, "—"] },
      { label: "Fade anytime, at home", values: [true, "Hard", false] },
      { label: "Waterproof, rinse-clean", values: [true, "Some", "—"] },
      { label: "240-min cordless runtime", values: [true, "Varies", "—"] },
      { label: "Cost in year one", values: ["$89.99", "$30–60", "$900+"] },
    ] as { label: string; values: (boolean | string)[] }[],
  },
  reddit: {
    eyebrow: "Real people, real fades",
    title: "Trusted by people who fade at home now.",
    sub: "Honest, unsponsored posts from people fading their own hair with this clipper.",
    labels: ["First self-fade attempt", "Second attempt — much sharper", "First experience, reviewed"],
    view: "View on Reddit",
    note: "Independent posts on Reddit — not paid or affiliated. Links open on reddit.com.",
  },
  trustedReddit: {
    title: "Real fades, straight from Reddit",
    subA: "Self-cutters across ",
    subHighlight: "r/SelfBarber",
    subB: " are posting their FadeClipper results.",
    postTitles: [
      "First self-fade with the FadeClipper — didn't expect the back to come out this clean",
      "Three weeks of practice + this clipper = barber-level fade at home",
      "Did the whole back fade solo using my phone camera. This thing basically blends itself",
    ],
  },
  offer: {
    bar: "Launch sale — save 40% today",
    h2: "Stop wasting money at barbers. Keep the clipper.",
    bullets: ["FadeClipper + full accessory kit", "Free worldwide shipping", "14-day money-back guarantee", "1-year warranty"],
    oneTime: "One-time payment · pays for itself in ~2 haircuts",
    cta: "Get FadeClipper",
    secure: "Secure checkout · Visa · Mastercard · PayPal",
  },
  faq: {
    eyebrow: "Questions",
    title: "Everything you're wondering.",
    items: [
      ["Can I really fade the back of my own head?", "Yes — that's exactly what FadeClipper is built for. The tapered 45° auto-fade blade blends the gradient as you glide up, so you don't need barber-level skill or two mirrors. Most people get a clean back fade on the first or second try."],
      ["Is it hard to use if I've never faded before?", "No. Pick a length and glide it flat around your head — the blade does the blending. Follow the four steps above and you'll have a sharp fade in minutes."],
      ["How long does the battery last?", "Up to 240 minutes of cordless runtime per charge — weeks of fades. The display shows exactly how many minutes remain, and it charges over USB-C on the dock."],
      ["Is it actually waterproof?", "Yes. You can fade in the shower and rinse the whole clipper under the tap. Cleanup takes about ten seconds."],
      ["What if I don't like it?", "You're covered by a 14-day money-back guarantee. If it isn't for you, send it back for a full refund."],
    ] as [string, string][],
  },
  finalCta: {
    title: "Your next fade is on you.",
    sub: "The auto-fading clipper that turns a barber-only skill into a one-swipe move.",
    cta: "Get FadeClipper — ",
    note: "14-day money-back guarantee · Free worldwide shipping",
  },
  footer: {
    tagline: "The auto-fading clipper. One swipe, fade done.",
    col1: [["How it works", "/#how"], ["Why FadeClipper", "/#compare"], ["Reviews", "/#reviews"], ["How to fade your own hair", "/how-to-fade-your-own-hair"], ["FAQ", "/#faq"]] as [string, string][],
    col2: [["About us", "/about"], ["Contact", "/contact"], ["Shipping", "/shipping"], ["Returns & refunds", "/returns"], ["Terms", "/terms"], ["Privacy", "/privacy"]] as [string, string][],
    rights: "All rights reserved.",
  },
  buyBox: {
    reviews: "reviews",
    title: "FadeClipper",
    sub: "The auto-fading cordless hair clipper.",
    save: "Save 40%",
    saleEndsIn: "Sale ends in",
    buyNow: "Buy now — ",
    startingCheckout: "Starting checkout…",
    perks: ["Free shipping", "Free guard set", "Digital guide"],
    inStock: "In stock",
    inStockRest: "order today, ships within 24 hours",
  },
  common: {
    seeHowItWorks: "See how it works",
    showMore: "Show more reviews",
    freeDelivery: "Free delivery",
    to: "to",
    arrives: "arrives",
    businessDays: "7–10 business days",
  },
  consent: {
    currencyPrompt: "Choose the currency you'd like to see prices in.",
    showUsd: "Show USD ($)",
    show: "Show",
    cookiePre: "We use cookies to improve your experience. By continuing you agree to our ",
    terms: "Terms",
    cookieMid: " & ",
    privacy: "Privacy",
    cookiePost: ".",
    essentialOnly: "Essential only",
    acceptAgree: "Accept & agree",
  },
  checkout: {
    secure: "Secure checkout",
    loading: "Loading secure checkout…",
    orderSummary: "Order summary",
    express: "Express checkout",
    or: "OR",
    contact: "Contact",
    email: "Email",
    emailNote: "Your order confirmation & receipt are sent here.",
    delivery: "Delivery",
    shippingMethod: "Shipping method",
    free: "FREE",
    standardLabel: "Standard shipping",
    standardEta: "7–10 business days",
    expressLabel: "Express shipping",
    expressEta: "2–3 business days",
    payment: "Payment",
    paymentSecure: "All transactions are secure and encrypted.",
    processing: "Processing…",
    payNow: "Pay now",
    poweredBy: "Powered by Stripe · Backed by our 14-day money-back guarantee",
    each: "each",
    addDiscount: "Add discount",
    discountCode: "Discount code",
    apply: "Apply",
    discountApplied: "Discount applied.",
    codeInvalid: "That code isn't valid.",
    subtotal: "Subtotal",
    discount: "Discount",
    shipping: "Shipping",
    freeWord: "Free",
    total: "Total",
    emailInvalid: "Please enter a valid email address.",
    payErr: "Payment could not be completed.",
    networkErr: "Network error — please try again.",
    couldNotStart: "Could not start checkout.",
    notConfigured: "Stripe isn't configured yet. Add your publishable key to go live.",
    continueSecure: "Continue to secure checkout",
    starting: "Starting…",
    backToProduct: "Back to product",
    policies: [["Refund policy", "/returns"], ["Shipping", "/shipping"], ["Privacy policy", "/privacy"], ["Terms of service", "/terms"], ["Contact", "/contact"]] as [string, string][],
  },
  success: {
    loading: "Loading your order…",
    order: "Order",
    thankYou: "Thank you",
    confirmedA: "Your order is confirmed",
    emailOnWay: " — a confirmation email is on its way to ",
    confirmedB: ". We'll email your tracking number as soon as it ships.",
    orderDetails: "Order details",
    contact: "Contact",
    payment: "Payment",
    paidVia: "Paid securely via Stripe",
    shippingAddress: "Shipping address",
    billingAddress: "Billing address",
    sameAsShipping: "Same as shipping address",
    shippingMethod: "Shipping method",
    arrivesInAbout: "arrives in about",
    continueShopping: "Continue shopping",
    needHelp: "Need help with your order?",
    orderSummary: "Order summary",
  },
  reviews: {
    heading: "Reviews by our customers",
    verified: "Verified buyers · updated daily",
    basedOn: "Based on",
    reviewsWord: "reviews",
    sortRelevant: "Most relevant",
    sortRecent: "Most recent",
    sortHigh: "Highest rated",
    sortLow: "Lowest rated",
    allRatings: "All ratings",
    stars5: "5 stars",
    stars4: "4 stars",
    stars3: "3 stars",
    stars2: "2 stars",
    stars1: "1 star",
    showing: "Showing",
    of: "of",
    reply: "Reply",
    disclaimer: "Reviews reflect individual experiences. Results vary with hair type and technique.",
    firstNames: ["Marcus", "Andre", "Dwayne", "Jordan", "Kevin", "Carlos", "Ethan", "Sam", "Marco", "Tyler", "Malik", "Liam", "Noah", "James", "Lucas", "Mason", "Diego", "Brian", "Victor", "Omar", "Isaac", "Nathan", "Ryan", "Cole", "Felix", "Shane", "Troy", "Derek", "Leon", "Xavier"],
    titles: ["Sharpest fade I've done at home", "Barber-level results", "No more expensive cuts", "Blends like magic", "So easy to use", "Better than my old clippers", "Worth every penny", "My go-to now", "Clean fade every time", "Impressed by the battery", "Quiet and powerful", "Saved me so much money", "Perfect for beginners", "The battery display is genius", "Basically fades itself", "Shower cuts changed the game", "Family clipper now", "Wish I'd bought it sooner", "Professional results at home", "Cuts thick hair with ease"],
    pos: [
      "The 45° blade does the blending for you — my fade looks even without any skill. Genuinely surprised.",
      "Charged it once and it's still going strong two weeks later. The minutes-left display is so handy.",
      "Waterproof means I fade in the shower and rinse it clean in seconds. Cleanup used to be the worst part.",
      "Went from paying the barber every two weeks to doing it myself. Paid for itself almost immediately.",
      "Thick, coarse hair here — turned the power up and it powered through with zero snagging.",
      "Used my phone for the back and the guide made it easy. First attempt looked way better than expected.",
      "The four fade lengths on one lever make it foolproof. No guessing which guard to grab.",
      "Blends the gradient at the back of my head that I could never do with normal clippers.",
      "Quieter than my old pair and doesn't get hot even after a full cut. Really well built.",
      "Bought it skeptical, now the whole house uses it. Kids' cuts included.",
      "Delivery was quick and it was well packaged. The fade came out sharp on the first go.",
      "Feels premium and solid, not cheap and plasticky like the ones I've had before.",
      "My line-up and fade finally look like the shop. Massive upgrade from my old trimmer.",
      "Holds a charge for weeks of cuts. The display reminds me before it runs low.",
      "Honestly idiot-proof. If you can comb your hair you can run this thing.",
    ],
    mixedTitles: ["Good but takes a little practice", "Solid, minor learning curve", "Great tool — go slow at first", "Happy overall, small nitpick", "Works well after a couple tries", "Nearly perfect"],
    mixed: [
      "Blends well but my first fade was uneven — my technique, not the clipper. By the third cut it clicked.",
      "Great clipper, just wish it came with a travel case for the guards.",
      "Took a couple tries to get the back right with my phone camera, but now it's quick.",
      "Powerful and sharp; the guards could click on a touch more firmly.",
      "Does the job well. Battery is great; instructions could be a bit clearer for total beginners.",
      "Solid fade once you find the angle — give yourself one practice run and you're set.",
    ],
    lowTitles: ["Arrived faulty — refunded fast", "Dead on arrival, but sorted quickly", "Didn't work out, got my money back", "Faulty unit — support made it right", "Stopped working, they replaced it", "Not my experience, but well handled"],
    low: [
      "Mine wouldn't power on out of the box, which was disappointing. I emailed support and had a full refund within two days, no arguing. Not what I hoped for, but handled properly.",
      "The first one died after a single charge. To their credit they shipped a replacement straight away and it's worked fine since — rough start, sorted in the end.",
      "Charging port on my unit was faulty. Customer service refunded me the same day I reached out. Can't fault how they dealt with it, just unlucky with the clipper.",
      "Battery wouldn't hold a charge. I asked for a refund and got it back quickly, no questions asked. Shame, because the one fade I managed looked good.",
      "Turned up with a loose, rattling blade. I sent a photo and they refunded in full within 48 hours. Didn't work out for me, but the support was solid.",
      "Stopped turning on after about a week. Expected a hassle and instead got a replacement in a few days. They made it right.",
    ],
    dates: [["2 days ago", 2], ["3 days ago", 3], ["4 days ago", 4], ["6 days ago", 6], ["1 week ago", 8], ["2 weeks ago", 15], ["3 weeks ago", 22], ["4 weeks ago", 28], ["1 month ago", 34], ["6 weeks ago", 44], ["2 months ago", 62], ["3 months ago", 92]] as [string, number][],
  },
};

export type SiteContent = typeof en;

const da: SiteContent = {
  nav: {
    links: [
      ["Sådan virker det", "/#how"],
      ["Hvorfor FadeClipper", "/#compare"],
      ["Anmeldelser", "/#reviews"],
      ["FAQ", "/#faq"],
    ],
    getYours: "Køb nu",
    offerEndsIn: "Tilbud slutter om",
    launchSale: "40% rabat — Lancering",
    reviews: "anmeldelser",
    subline: "+ gratis kit & 14-dages garanti",
    bladeBullet: "45° auto-fade-blad",
    waterproofBullet: "Vandtæt, 240 min. batteri",
    buyNow: "Køb nu",
    startingCheckout: "Starter betaling…",
  },
  hero: {
    reviews: "anmeldelser",
    h1a: "Fade dit eget hår.",
    h1b: "På få minutter.",
    subA: "Den auto-fadende trimmer med et 45° blad, der blender overgangen for dig — ",
    subEmph: "helt uden erfaring",
    orderNow: "Bestil nu — ",
    securePayment: "Sikker betaling",
    guarantee: "14 dages garanti",
    videoAlt: "FadeClipper auto-fadende trådløs hårtrimmer",
  },
  press: { seenIn: "Omtalt i…" },
  how: {
    eyebrow: "Klar på 60 sekunder",
    title: "Hvordan virker det?",
    sub: "Ingen erfaring nødvendig. Kan du rede dit hår, kan du bruge en FadeClipper.",
    steps: [
      { title: "Oplad & tænd", text: "Sæt den i holderen til den er fuld, og tryk på tænd/sluk. Displayet viser batteri og resterende køretid." },
      { title: "Vælg din fade-længde", text: "Skub grebet til 0,4, 0,8 eller 1,2 mm. Start lavt og tæt ved nakken, og gå gradvist op, når du bevæger dig højere op." },
      { title: "Glid henover faden", text: "Hold den fladt mod huden og glid lige henover siden. Bladet blender overgangen for dig." },
      { title: "Blend & afslut", text: "Sæt længden et hak op og kør lidt højere for at smelte linjerne sammen til en jævn, skarp fade." },
    ],
  },
  compare: {
    eyebrow: "Forskellen",
    title: "Derfor slår FadeClipper almindelige trimmere.",
    sub: "Auto-fade-bladet gør det, almindelige trimmere ikke kan — og det, barberen tager penge for, igen og igen.",
    cols: ["FadeClipper", "Almindelig", "Barber"],
    you: "Dig",
    rows: [
      { label: "Auto-fader & blender for dig", values: [true, false, true] },
      { label: "Ingen erfaring eller ekstra spejl", values: [true, false, "—"] },
      { label: "Fade når som helst, derhjemme", values: [true, "Svært", false] },
      { label: "Vandtæt, skyl ren", values: [true, "Nogle", "—"] },
      { label: "240 min. trådløs køretid", values: [true, "Varierer", "—"] },
      { label: "Pris det første år", values: ["620 kr.", "200–400 kr.", "6.000+ kr."] },
    ],
  },
  reddit: {
    eyebrow: "Rigtige folk, rigtige fades",
    title: "Brugt af folk, der nu fader derhjemme.",
    sub: "Ærlige, usponsorerede opslag fra folk, der fader deres eget hår med denne trimmer.",
    labels: ["Første forsøg på selv-fade", "Andet forsøg — meget skarpere", "Første oplevelse, anmeldt"],
    view: "Se på Reddit",
    note: "Uafhængige opslag på Reddit — ikke betalt eller tilknyttet. Links åbner på reddit.com.",
  },
  trustedReddit: {
    title: "Rigtige fades, direkte fra Reddit",
    subA: "Folk, der klipper sig selv på ",
    subHighlight: "r/SelfBarber",
    subB: ", deler deres FadeClipper-resultater.",
    postTitles: [
      "Første selv-fade med FadeClipper — havde ikke regnet med, at nakken blev så ren",
      "Tre ugers øvelse + denne trimmer = barber-agtig fade derhjemme",
      "Fadede hele nakken selv med telefonkameraet. Den her blender nærmest sig selv",
    ],
  },
  offer: {
    bar: "Lanceringstilbud — spar 40% i dag",
    h2: "Stop med at bruge penge hos barberen. Behold trimmeren.",
    bullets: ["FadeClipper + komplet tilbehørssæt", "Gratis fragt i hele verden", "14 dages pengene-tilbage-garanti", "1 års garanti"],
    oneTime: "Engangskøb · tjener sig hjem på ~2 klipninger",
    cta: "Køb FadeClipper",
    secure: "Sikker betaling · Visa · Mastercard · PayPal",
  },
  faq: {
    eyebrow: "Spørgsmål",
    title: "Alt det, du går og tænker på.",
    items: [
      ["Kan jeg virkelig fade min egen nakke?", "Ja — det er præcis det, FadeClipper er bygget til. Det skrå 45° auto-fade-blad blender overgangen, mens du glider op, så du hverken skal have barber-erfaring eller to spejle. De fleste får en ren nakke-fade i første eller andet forsøg."],
      ["Er det svært, hvis jeg aldrig har fadet før?", "Nej. Vælg en længde og glid den fladt rundt om hovedet — bladet klarer blendingen. Følg de fire trin ovenfor, og du har en skarp fade på få minutter."],
      ["Hvor længe holder batteriet?", "Op til 240 minutters trådløs køretid pr. opladning — flere ugers fades. Displayet viser præcis, hvor mange minutter der er tilbage, og den oplades via USB-C i holderen."],
      ["Er den virkelig vandtæt?", "Ja. Du kan fade i badet og skylle hele trimmeren under vandhanen. Rengøring tager omkring ti sekunder."],
      ["Hvad hvis jeg ikke er tilfreds?", "Du er dækket af 14 dages pengene-tilbage-garanti. Er den ikke noget for dig, sender du den bare retur og får hele beløbet igen."],
    ],
  },
  finalCta: {
    title: "Din næste fade er op til dig.",
    sub: "Den auto-fadende trimmer, der gør en barber-only-skill til ét enkelt swipe.",
    cta: "Køb FadeClipper — ",
    note: "14 dages pengene-tilbage-garanti · Gratis fragt i hele verden",
  },
  footer: {
    tagline: "Den auto-fadende trimmer. Ét swipe, faden er klar.",
    col1: [["Sådan virker det", "/#how"], ["Hvorfor FadeClipper", "/#compare"], ["Anmeldelser", "/#reviews"], ["Sådan fader du selv", "/how-to-fade-your-own-hair"], ["FAQ", "/#faq"]],
    col2: [["Om os", "/about"], ["Kontakt", "/contact"], ["Fragt", "/shipping"], ["Returnering & refusion", "/returns"], ["Handelsbetingelser", "/terms"], ["Privatliv", "/privacy"]],
    rights: "Alle rettigheder forbeholdes.",
  },
  buyBox: {
    reviews: "anmeldelser",
    title: "FadeClipper",
    sub: "Den auto-fadende trådløse hårtrimmer.",
    save: "Spar 40%",
    saleEndsIn: "Tilbud slutter om",
    buyNow: "Køb nu — ",
    startingCheckout: "Starter betaling…",
    perks: ["Gratis fragt", "Gratis kamsæt", "Digital guide"],
    inStock: "På lager",
    inStockRest: "bestil i dag, sendes inden for 24 timer",
  },
  common: {
    seeHowItWorks: "Se hvordan det virker",
    showMore: "Vis flere anmeldelser",
    freeDelivery: "Gratis fragt",
    to: "til",
    arrives: "leveres",
    businessDays: "7–10 hverdage",
  },
  consent: {
    currencyPrompt: "Vælg den valuta, du vil se priser i.",
    showUsd: "Vis USD ($)",
    show: "Vis",
    cookiePre: "Vi bruger cookies til at forbedre din oplevelse. Ved at fortsætte accepterer du vores ",
    terms: "Handelsbetingelser",
    cookieMid: " & ",
    privacy: "Privatlivspolitik",
    cookiePost: ".",
    essentialOnly: "Kun nødvendige",
    acceptAgree: "Accepter alle",
  },
  checkout: {
    secure: "Sikker betaling",
    loading: "Indlæser sikker betaling…",
    orderSummary: "Ordreoversigt",
    express: "Hurtig betaling",
    or: "ELLER",
    contact: "Kontakt",
    email: "E-mail",
    emailNote: "Din ordrebekræftelse og kvittering sendes hertil.",
    delivery: "Levering",
    shippingMethod: "Forsendelsesmetode",
    free: "GRATIS",
    standardLabel: "Standardforsendelse",
    standardEta: "7–10 hverdage",
    expressLabel: "Ekspresforsendelse",
    expressEta: "2–3 hverdage",
    payment: "Betaling",
    paymentSecure: "Alle transaktioner er sikre og krypterede.",
    processing: "Behandler…",
    payNow: "Betal nu",
    poweredBy: "Drevet af Stripe · Dækket af vores 14 dages pengene-tilbage-garanti",
    each: "stk.",
    addDiscount: "Tilføj rabatkode",
    discountCode: "Rabatkode",
    apply: "Anvend",
    discountApplied: "Rabat anvendt.",
    codeInvalid: "Koden er ikke gyldig.",
    subtotal: "Subtotal",
    discount: "Rabat",
    shipping: "Fragt",
    freeWord: "Gratis",
    total: "Total",
    emailInvalid: "Indtast en gyldig e-mailadresse.",
    payErr: "Betalingen kunne ikke gennemføres.",
    networkErr: "Netværksfejl — prøv igen.",
    couldNotStart: "Kunne ikke starte betaling.",
    notConfigured: "Stripe er ikke konfigureret endnu. Tilføj din publishable key for at gå live.",
    continueSecure: "Fortsæt til sikker betaling",
    starting: "Starter…",
    backToProduct: "Tilbage til produktet",
    policies: [["Refusionspolitik", "/returns"], ["Fragt", "/shipping"], ["Privatlivspolitik", "/privacy"], ["Handelsbetingelser", "/terms"], ["Kontakt", "/contact"]],
  },
  success: {
    loading: "Indlæser din ordre…",
    order: "Ordre",
    thankYou: "Tak",
    confirmedA: "Din ordre er bekræftet",
    emailOnWay: " — en bekræftelses-e-mail er på vej til ",
    confirmedB: ". Vi sender dig et sporingsnummer, så snart den afsendes.",
    orderDetails: "Ordredetaljer",
    contact: "Kontakt",
    payment: "Betaling",
    paidVia: "Betalt sikkert via Stripe",
    shippingAddress: "Leveringsadresse",
    billingAddress: "Faktureringsadresse",
    sameAsShipping: "Samme som leveringsadresse",
    shippingMethod: "Forsendelsesmetode",
    arrivesInAbout: "leveres om ca.",
    continueShopping: "Fortsæt med at handle",
    needHelp: "Brug for hjælp til din ordre?",
    orderSummary: "Ordreoversigt",
  },
  reviews: {
    heading: "Anmeldelser fra vores kunder",
    verified: "Verificerede købere · opdateres dagligt",
    basedOn: "Baseret på",
    reviewsWord: "anmeldelser",
    sortRelevant: "Mest relevante",
    sortRecent: "Nyeste først",
    sortHigh: "Højest bedømt",
    sortLow: "Lavest bedømt",
    allRatings: "Alle bedømmelser",
    stars5: "5 stjerner",
    stars4: "4 stjerner",
    stars3: "3 stjerner",
    stars2: "2 stjerner",
    stars1: "1 stjerne",
    showing: "Viser",
    of: "af",
    reply: "Svar",
    disclaimer: "Anmeldelser afspejler individuelle oplevelser. Resultatet varierer med hårtype og teknik.",
    firstNames: ["Mikkel", "Anders", "Frederik", "Emil", "Lucas", "Oliver", "Noah", "William", "Victor", "Magnus", "Sebastian", "Mathias", "Jonas", "Rasmus", "Christian", "Nikolaj", "Andreas", "Kasper", "Daniel", "Simon", "Tobias", "Jakob", "Marcus", "Benjamin", "Oscar", "Elias", "Aksel", "Silas", "Amir", "Yusuf"],
    titles: ["Skarpeste fade jeg har lavet selv", "Barber-agtigt resultat", "Slut med dyre klip", "Blender som magi", "Så nem at bruge", "Bedre end min gamle trimmer", "Hver krone værd", "Min faste nu", "Ren fade hver gang", "Imponeret over batteriet", "Stille og kraftfuld", "Har sparet mig mange penge", "Perfekt til begyndere", "Batteri-displayet er genialt", "Fader nærmest sig selv", "Klip i badet ændrede alt", "Familiens trimmer nu", "Skulle have købt den før", "Professionelt resultat hjemme", "Klarer tykt hår med lethed"],
    pos: [
      "45°-bladet klarer blendingen for dig — min fade ser jævn ud uden nogen erfaring. Ærligt talt overrasket.",
      "Ladede den én gang, og den kører stadig to uger efter. Displayet med minutter tilbage er super smart.",
      "Vandtæt betyder, at jeg fader i badet og skyller den ren på få sekunder. Rengøring plejede at være det værste.",
      "Gik fra barber hver anden uge til at gøre det selv. Den tjente sig hjem næsten med det samme.",
      "Tykt, kraftigt hår her — skruede op for styrken, og den kørte lige igennem uden at hive.",
      "Brugte telefonen til nakken, og guiden gjorde det nemt. Første forsøg blev meget bedre end ventet.",
      "De fire fade-længder på ét greb gør det idiotsikkert. Ingen tvivl om hvilket kamsæt man skal gribe.",
      "Blender overgangen i nakken, som jeg aldrig kunne med almindelige trimmere.",
      "Mere stille end min gamle, og den bliver ikke varm selv efter et helt klip. Rigtig godt bygget.",
      "Købte den skeptisk, nu bruger hele huset den. Børnenes klip inkluderet.",
      "Hurtig levering og godt pakket ind. Faden blev skarp i første forsøg.",
      "Føles gedigen og solid, ikke billig og plastikagtig som dem, jeg har haft før.",
      "Min optrimning og fade ligner endelig barberens. Kæmpe opgradering fra min gamle trimmer.",
      "Holder på strømmen i ugevis. Displayet minder mig om det, før den løber tør.",
      "Ærligt talt idiotsikker. Kan du rede dit hår, kan du styre den her.",
    ],
    mixedTitles: ["God, men kræver lidt øvelse", "Solid, lille indlæringskurve", "Godt værktøj — tag den med ro først", "Glad overordnet, lille anke", "Virker godt efter et par forsøg", "Næsten perfekt"],
    mixed: [
      "Blender godt, men min første fade blev lidt ujævn — min teknik, ikke trimmeren. Efter tredje klip sad den.",
      "Fin trimmer, ville bare ønske der fulgte en taske med til kamsættet.",
      "Tog et par forsøg at ramme nakken med telefonkameraet, men nu går det hurtigt.",
      "Kraftfuld og skarp; kamsættet kunne klikke lidt fastere på.",
      "Gør arbejdet fint. Batteriet er godt; vejledningen kunne være lidt klarere for helt nye.",
      "Solid fade når du finder vinklen — giv dig selv ét øve-klip, så er du klar.",
    ],
    lowTitles: ["Kom defekt — hurtigt refunderet", "Død ved ankomst, men klaret hurtigt", "Gik ikke, fik pengene igen", "Defekt enhed — support ordnede det", "Holdt op med at virke, de byttede den", "Ikke min oplevelse, men flot håndteret"],
    low: [
      "Min ville ikke tænde ud af æsken, hvilket var skuffende. Jeg skrev til support og fik fuld refusion inden for to dage, uden diskussion. Ikke hvad jeg håbede, men ordentligt håndteret.",
      "Den første døde efter én opladning. Til deres ros sendte de straks en ny, og den har virket fint siden — hård start, ordnet til sidst.",
      "Ladeporten på min var defekt. Kundeservice refunderede samme dag, jeg skrev. Kan ikke klage over håndteringen, bare uheldig med trimmeren.",
      "Batteriet kunne ikke holde strøm. Jeg bad om refusion og fik den hurtigt, uden spørgsmål. Ærgerligt, for den ene fade, jeg nåede, så godt ud.",
      "Kom med et løst, raslende blad. Jeg sendte et billede, og de refunderede fuldt inden for 48 timer. Gik ikke for mig, men supporten var solid.",
      "Holdt op med at tænde efter cirka en uge. Ventede bøvl og fik i stedet en ny inden for få dage. De gjorde det godt igen.",
    ],
    dates: [["2 dage siden", 2], ["3 dage siden", 3], ["4 dage siden", 4], ["6 dage siden", 6], ["1 uge siden", 8], ["2 uger siden", 15], ["3 uger siden", 22], ["4 uger siden", 28], ["1 måned siden", 34], ["6 uger siden", 44], ["2 måneder siden", 62], ["3 måneder siden", 92]],
  },
};

export const CONTENT: Record<Lang, SiteContent> = { en, da };
