// ISO 3166-1 alpha-2 code + display name, for the checkout country/region select.
// Denmark and the main shipping markets sit at the top; the rest are alphabetical.
export const COUNTRIES: [string, string][] = [
  ["DK", "Denmark"],
  ["US", "United States"],
  ["GB", "United Kingdom"],
  ["DE", "Germany"],
  ["SE", "Sweden"],
  ["NO", "Norway"],
  ["NL", "Netherlands"],
  ["FI", "Finland"],
  ["FR", "France"],
  ["IE", "Ireland"],
  ["—", "—————————————"],
  ["AU", "Australia"],
  ["AT", "Austria"],
  ["BE", "Belgium"],
  ["BG", "Bulgaria"],
  ["CA", "Canada"],
  ["HR", "Croatia"],
  ["CY", "Cyprus"],
  ["CZ", "Czechia"],
  ["EE", "Estonia"],
  ["GR", "Greece"],
  ["HK", "Hong Kong"],
  ["HU", "Hungary"],
  ["IS", "Iceland"],
  ["IN", "India"],
  ["ID", "Indonesia"],
  ["IL", "Israel"],
  ["IT", "Italy"],
  ["JP", "Japan"],
  ["LV", "Latvia"],
  ["LT", "Lithuania"],
  ["LU", "Luxembourg"],
  ["MY", "Malaysia"],
  ["MT", "Malta"],
  ["MX", "Mexico"],
  ["NZ", "New Zealand"],
  ["PL", "Poland"],
  ["PT", "Portugal"],
  ["RO", "Romania"],
  ["SG", "Singapore"],
  ["SK", "Slovakia"],
  ["SI", "Slovenia"],
  ["ZA", "South Africa"],
  ["KR", "South Korea"],
  ["ES", "Spain"],
  ["CH", "Switzerland"],
  ["TW", "Taiwan"],
  ["TH", "Thailand"],
  ["TR", "Türkiye"],
  ["AE", "United Arab Emirates"],
  ["AR", "Argentina"],
  ["BR", "Brazil"],
  ["CL", "Chile"],
  ["CO", "Colombia"],
  ["PH", "Philippines"],
  ["SA", "Saudi Arabia"],
  ["VN", "Vietnam"],
];
